name: commit-hook

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Code Formatting
        run: |
          black .
      - name: Commit files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "black code formatting" -a
          else
            echo "no changes";
          fi
          
          echo "commiting to: ${GITHUB_REF##*/}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
